Noticeboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('NoticeBoard/', include('board.urls')),
    path('Member/',include('member.urls'))
]

board/urls.py
from django.urls import path, include
from board import views

app_name ="noticeboard"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:text_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:text_id>/update', views.update, name='update'),
    path('<int:text_id>/delete', views.delete, name='delete'),
    path('<int:text_id>/comment_create', views.comment_create, name='comment_create'),
]

member/urls.py
from django.urls import path, include
from member import views

app_name ="member"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout', views.logout, name='logout'),
]

board/models.py
from django.db import models

# Create your models here.

class Create(models.Model):
    title = models.CharField(max_length=20, db_column='title')
    contents = models.TextField(max_length=1000, db_column='contents')
    author = models.CharField(max_length=10, db_column='author') # 글쓴이 입력 칸 마련 (기본 익명)
    create_date = models.DateTimeField(auto_now_add=True) # 글 생성일
    
    def __str__(self):
        return f"{self.title}, {self.author}, {self.contents}, {self.id}, {self.create_date}"

    

class Comment(models.Model):
    comment_id = models.ForeignKey(Create, on_delete=models.CASCADE, db_column='comment_id') # Create 클래스의 id를 외래키로 참조
    contents = models.CharField(max_length=100, db_column='contents')
    create_date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=10, db_column='author')
    
    def __str__(self):
        return f"{self.contents},{self.create_date}"

member/models.py
from django.db import models

# Create your models here.

board/forms.py
from django import forms
from board.models import Create, Comment

class CreateForm(forms.ModelForm):
    class Meta:
        model = Create
        fields = ['title','contents']
        labels = {'title':'제목', 'contents':'내용'}

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Create, Comment
from django.core.paginator import Paginator
from .forms import CreateForm
from django.contrib.auth.decorators import login_required

def index(request):
    page = request.GET.get('page', '1') # 페이지 구현
    text_list = Create.objects.order_by('-create_date')
    paginator = Paginator(text_list, 5) # 10개 씩
    page_obj = paginator.get_page(page)
    content = {'text_list':page_obj,}
    return render(request, "board/index.html", content)

def detail(request, text_id):
    text_list = get_object_or_404(Create, pk=text_id)
    comment_list = Comment.objects.filter(comment_id = text_id).order_by('create_date')
    present_user = request.user
    create_author = text_list.author
    user_dict = {'present_user':str(present_user), 'create_author':str(create_author)}
    content = {'text_list':text_list,
               'comment_list':comment_list,
               'text_id': text_id,
               'user_dict':user_dict}
    return render(request, 'board/detail.html', content)

@login_required(login_url='member:login')
def create(request):
    if request.method == "POST": 
       form = CreateForm(request.POST)
       if form.is_valid():
           post = form.save(commit=False)
           post.author = request.user
           post = form.save()
           return redirect(f'/NoticeBoard/{post.id}')
       
       else:
            form = CreateForm()
            context = {'form':form}
            return render(request, 'board/create.html',context)

    else:
        form = CreateForm()
        context = {'form':form}
        return render(request, 'board/create.html',context)

@login_required(login_url='member:login')
def update(request, text_id):
    text_list = get_object_or_404(Create, pk=text_id)
    if request.method == "GET":
        form = CreateForm(instance=text_list)
        content = {'form':form,
                   'text_id':text_id}
        return render(request, 'board/update.html', content)
    
    else:
        form = CreateForm(request.POST, instance=text_list)
        if form.is_valid():
            post = form.save(commit=False)
            post = form.save()
        return redirect(f'/NoticeBoard/{post.id}')

@login_required(login_url='member:login')
def delete(request, text_id):
    delete_notice = get_object_or_404(Create, pk=text_id)
    delete_notice.delete()
    return redirect('/NoticeBoard')

@login_required(login_url='member:login')
def comment_create(request, text_id):
    content={'text_id':text_id}

    if request.method == "POST":
        create_instance = get_object_or_404(Create, pk=text_id)
        new_comment = Comment.objects.create(comment_id=create_instance, contents=request.POST['fcomment'], author=request.user)
        return redirect(f'/NoticeBoard/{text_id}')

    else:
        return render(request, 'board/detail.html',content)

member/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib import auth

# Create your views here.
def index(request):
    return HttpResponse("로그인 앱 view_index")

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = auth.authenticate(
                request=request,
                username=username,
                password=password
            )
            if user is not None:
                auth.login(request, user)
                next_value = request.GET.get("next")
                if next_value:
                    return redirect(next_value)
                else:
                    return redirect('/NoticeBoard')
        
        else:
            non_error = form.non_field_errors
            context = {'non_error':non_error,'form':form}
            return render(request, 'member/login.html', context)
            
    else:
        form = AuthenticationForm()
        context = {'form' : form}
        return render(request, 'member/login.html', context)
    
def logout(request):
   auth.logout(request)
   return redirect('/NoticeBoard')

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            return redirect('/NoticeBoard')    

    else:
        form = UserCreationForm()
        
    return render(request, 'member/signup.html', {'form':form})
    

board/templates/board/create.html
{% extends 'base.html'  %}


{%block contents%}
<!-- 본문  -->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글쓰기</h5>
    <form action="{% url 'noticeboard:create' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="contents" class="form-label">내용</label>
            <textarea name="contents" id="contents" class="form-control" rows="10">{{ form.contents.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

board/templates/board/detail.html
{% extends 'base.html'  %}

{%block contents%}
    
<div class="container my-3">
    <!-- 본문  -->
    <h2 class="border-bottom py-2">{{text_list.title}}</h2>
    <div class="d-flex justify-content-end my-3">
        <div class="badge  text-dark">
            {{text_list.author}} - 
            {{text_list.create_date}}
        </div>
    </div>
     <div class="card text-dark bg-light my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{text_list.contents}}
            </div>
        </div>
     </div>

    <!-- 삭제, 수정 버튼  -->
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        {% if user_dict.present_user == user_dict.create_author%}
            <button class="btn btn-primary" type="button" onClick="location.href='update'">수정</button>
            <form action="{% url 'noticeboard:delete' text_id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">삭제</button>
            </form>
        {% endif %}
    </div>
    

    <!-- 댓글  -->
    <h6 class="border-bottom py-2">댓글</h6>
    <!-- 댓글 작성-->
    
    <form action="{% url 'noticeboard:comment_create' text_id %}" method="post">
        {% csrf_token %}
        <div class="row justify-content-between">
            <div class="col-10">
                <input class="form-control" type='text' name='fcomment'>
            </div>
            <div class="col-auto">
                <button class="btn btn-primary" type="submit">댓글작성</button>
            </div>
            
        </div>
    </form>

    <!-- 댓글 목록 -->
        {% if comment_list %}
            {% for comment in comment_list %}
            <div class="card text-dark bg-light mx-3 my-3">
                <div class="mx-2 my-2">
                    {{ comment.contents }}
                    <div class="d-flex justify-content-end">
                        <div class="badge  text-dark">
                            {{comment.author}} - {{comment.create_date}}
                        </div>
                    </div>
                </div>
                
            </div>
            {% endfor %}
        {% else %}
            <h6 class="border-bottom py-2">No comment are available.</h6>
        {% endif %}
    </div>
</div>
{% endblock %}

board/templates/board/index.html
{% extends 'base.html'  %}

{%block contents%}

<!-- 글 목차  -->
<div class="container my-4">
    <div class="row g-4">
        {% if text_list %}
            {% for text in text_list %}
            <div class="card shadow-sm">
                <div class="card-body">
                    <p class="card-text">{{ text.title }}</p>
                    <hr>
                    <p class="card-text">{{ text.contents|truncatechars:45 }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'noticeboard:detail' text.id %}'" >View</button>
                        </div>
                        <small class="text-muted">{{text.author}} - {{text.create_date}}</small>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <p>No contents are available.</p>
        {% endif %}
    </div>

    <!-- 글 작성 버튼 -->
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <form action="{% url 'noticeboard:create' %}" method="get">
            {% csrf_token %}
            <input type="submit" value="글쓰기" class="btn btn-primary float-right my-3">
        </form>
    </div>

<!-- 페이지네이션  -->
    <ul class="pagination justify-content-center my-3">
        <!-- 이전페이지 -->
        {% if text_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ text_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}

        <!-- 페이지리스트 -->
        {% for page_number in text_list.paginator.page_range %}
        {% if page_number >= text_list.number|add:-5 and page_number <= text_list.number|add:5 %}
        {% if page_number == text_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if text_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ text_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
</div>

{%endblock%}

board/templates/board/update.html
{% extends 'base.html'  %}

{%block contents%}
<!-- 본문  -->
<div class="container">
    <h5 class="my-3 border-bottom pb-2">수정하기</h5>
    <form action="{% url 'noticeboard:update' text_id %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                value="{{form.title.value}}">
        </div>
        <div class="mb-3">
            <label for="contents" class="form-label">내용</label>
            <textarea name="contents" id="contents" class="form-control" rows="10">{{form.contents.value}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

member/templates/member/login.html
{% extends 'base.html'  %}

{%block contents%}
<div class="container my-3">
    <form action="{% url 'member:login' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <!-- error -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for input_field in form %}
            {% if input_field.errors %}
            <div>
                {{input_field.label}} : {{input_field.errors}}
            </div>
            {% endif %}
            {% endfor %}

            {% for error in non_error %}
            <div>
                {{error}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <!-- input_field -->
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{%endblock%}

<ul class="errorlist">
    
    <li>username
        <ul class="errorlist">
            <li>필수 항목입니다.</li>
        </ul>
    </li>

    <li>password
        <ul class="errorlist">
                <li>필수 항목입니다.</li>
        </ul>
    </li>

</ul>
    

member/templates/member/signup.html
{% extends 'base.html'  %}

{%block contents%}
<div class="container my-3">
    <form action="{% url 'member:signup' %}" method="POST">
        {% csrf_token %}
        <!-- error -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for input_field in form %}
            {% if input_field.errors %}
            <div>
                {{input_field.label}} : {{input_field.errors}}
            </div>
            {% endif %}
            {% endfor %}

            {% for error in form.non_field_errors %}
            <div>
                {{error}}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2">
        </div>
        <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
</div>
{%endblock%}

{{form.errors}}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NoticeBoard</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <script src="{% static 'bootstrap.min.js' %}"></script>
</head>
<body class = "d-flex flex-column min-vh-100">
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand">NoticeBoard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href='/NoticeBoard'>Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/minzunea/Noticeboard">Git</a>
            </li>
          </ul>

          {% if user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">{{request.user}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'member:logout' %}" aria-disabled="true">로그아웃</a>
            </li>
          </ul>

         {% else %}
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/Member/login">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/Member/signup">회원가입</a>
            </li>
          </ul>
         {% endif %}
        </div>
      </div>
    </nav>

    <!-- contents  -->
    {% block contents%}{% endblock %}

    <div class="container mt-auto">
      <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href='/NoticeBoard' class="nav-link px-2 text-muted">Home</a></li>
          <li class="nav-item"><a href="https://github.com/minzunea/Noticeboard" class="nav-link px-2 text-muted">Git</a></li>
        </ul>
        <p class="text-center text-muted">2024 Minzunea</p>
      </footer>
    </div>

</body>
</html>